--- #YAML:1.0
name: Posy-Plugin-CgiCarp
version: 0.40
author:
  - Kathryn Andersen
abstract: Posy plugin to aid debugging by using CGI::Carp
license: perl
requires:
  CGI::Carp: 1.27
  Posy: 0.4
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::CgiCarp:
    file: lib/Posy/Plugin/CgiCarp.pm
    version: 0.40
generated_by: Module::Build version 0.2607
